### ISSUE TITLE
I cannot store or repair my car

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#419]
#### __Description__ 
So I accidentally jumped out of my car and crashed, I had to go on a call, and when I got back to take my car to benny's I went down there, and I couldn't reapir my car that was obviously very much damaged. Then I gave up and decided to park my car. And I cannot store my car. :( Not fun.. so um Yeah I don't know what yo do.
#### __Evidence__ 
https://i.imgur.com/MlIxcsX.jpg
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Sayahchan
**Coordinates** | vector3(282.2185, -329.5242, 44.7424)
**Steam ID** | steam:11000010413aae1
**Discord ID** | discord:397959613061791745
**Citizen ID** | FFU45850
**Character Name** | Charlene Garcia

**Comment by Dimmies** [comment]
I was able to replicate this, but unsure of what's causing this to happen. Seems to be related to not being able to impound and dv vehicles. If anyone has any more information on this, feel free to add.

**Comment by Dimmies** [comment]
#### __Description__ 
After collecting a broken down/abandoned car with teh flatbed and taking it to the impound yard, I was unable to get the prompt to impound the vehicle whilst it was in the correct area. I can only presume this was because it was broken down and the engine wouldn't start. I was able to impound a local car and also got the prompt to impound my truck.
#### __Evidence__ 
https://imgur.com/fyw7OAt
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Chuff
**Coordinates** | vector3(-238.0416, -1181.076, 22.69028)
**Steam ID** | steam:110000101c301ed
**Discord ID** | discord:147386472016642058
**Citizen ID** | FHO94294
**Character Name** | Tommy Jenkins

**Comment by Dimmies** [comment]
#### __Description__ 
PD and civilian cars cant be impounded. Tried Inside, tried outside, cant return them to the PD garage, cant DV them
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Pyotr Palach
**Coordinates** | vector3(-57.61024, -1114.099, 26.43632)
**Steam ID** | steam:11000011b56c5c4
**Discord ID** | discord:612497931169169408
**Citizen ID** | USC02137
**Character Name** | Pyotr Palach

**Comment by Dimmies** [comment]
#### __Description__ 
Attempting to store my vehicle in the Pink Motel Garage, and it will not allow me to store it. No error message, just nothing when I press E.
#### __Evidence__ 
http://img.firav.us/images/2021/10/16/FiveM_b2189_GTAProcess_2021-10-16_21-28-37.png
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Firav
**Coordinates** | vector3(289.5783, -340.3627, 44.48625)
**Steam ID** | steam:110000106bee631
**Discord ID** | discord:255140640965263360
**Citizen ID** | TPZ08138
**Character Name** | Kevin Baumann

**Comment by Dimmies** [comment]
#### __Description__ 
Legion garage and no other garage won't let me store my personal vehicle
#### __Evidence__ 
https://i.imgur.com/epU7VLL.png
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | NadeFrame
**Coordinates** | vector3(224.7167, -819.4489, 30.03263)
**Steam ID** | steam:110000110adcb80
**Discord ID** | discord:262487501434912768
**Citizen ID** | QPY65340
**Character Name** | Drake Carter
