### ISSUE TITLE
Inventory Scuff / Eddie Russo / Administries#0001

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#421]
#### __Description__ 
I guess the inventory didn't update quick enough after reopening a few times and I lost over 55 Gold Bars :(
#### __Evidence__ 
I have a clip I can share over Discord!
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Eddie Russo
**Coordinates** | vector3(1096.529, -1979.9, 31.01467)
**Steam ID** | steam:11000010b0b0a55
**Discord ID** | discord:154619574153641984
**Citizen ID** | ILT88962
**Character Name** | Eddie Russo

**Comment by Dimmies** [comment]
https://user-images.githubusercontent.com/28818644/132968907-a96ec975-2a8c-470a-a885-b2af3f207f17.mp4

Has a current weight of 136, adds 37 gold bar which is 55lbs, should be 191lbs in total but it says he's full and removes the items. Then when he closes/reopens the inventory he's at 176lbs.

- Need to handle drag/drop items when you're full (instead of deleting the items, just move it back to the fromSlot)
- Need to figure out why his inventory showed 136lbs but then said 176

If anyone can replicate this, let me know!
